histgradient_boost:
  learning_rate: 0.004808654503100462
  max_bins: 205
  max_depth: 5
  max_iter: 900
  min_samples_leaf: 1
  tol: 0.0027585422591514643
lgbm_regressor:
  boosting_type: gbdt
  colsample_bytree: 0.4
  learning_rate: 0.01880708907149719
  max_depth: 5
  min_child_samples: 35
  n_estimators: 1660
  num_leaves: 52
  objective: rmse
  subsample: 0.9
random_forest:
  max_depth: null
  min_samples_leaf: 3
  min_samples_split: 4
  n_estimators: 900
xgb_regressor:
  booster: gbtree
  colsample_bytree: 0.7
  learning_rate: 0.08165628613947787
  max_bin: 105
  max_depth: 5
  max_leaves: 75
  n_estimators: 1560
  objective: reg:squarederror
  subsample: 0.9
  tree_method: hist
