histgradient_boost:
  learning_rate: 0.0010803316249124693
  max_bins: 115
  max_depth: 7
  max_iter: 1680
  min_samples_leaf: 2
  tol: 0.004115113552287994
lgbm_regressor:
  boosting_type: gbdt
  colsample_bytree: 0.9
  learning_rate: 0.007014265785524425
  max_depth: null
  min_child_samples: 40
  n_estimators: 1740
  num_leaves: 46
  objective: rmse
  subsample: 0.4
random_forest:
  max_depth: null
  min_samples_leaf: 3
  min_samples_split: 5
  n_estimators: 1920
xgb_regressor:
  booster: gbtree
  colsample_bytree: 0.7
  learning_rate: 0.003969206694178654
  max_bin: 100
  max_depth: 7
  max_leaves: 15
  n_estimators: 1740
  objective: reg:squarederror
  subsample: 0.4
  tree_method: hist
