histgradient_boost:
  learning_rate: 0.029365444432236033
  max_bins: 65
  max_depth: null
  max_iter: 860
  min_samples_leaf: 4
  tol: 0.00017739272256200877
lgbm_regressor:
  boosting_type: dart
  colsample_bytree: 0.9
  learning_rate: 0.05728034516464531
  max_depth: 5
  min_child_samples: 80
  n_estimators: 1380
  num_leaves: 80
  objective: rmse
  subsample: 0.9
random_forest:
  max_depth: null
  min_samples_leaf: 3
  min_samples_split: 4
  n_estimators: 920
xgb_regressor:
  booster: gbtree
  colsample_bytree: 0.5
  learning_rate: 0.0022805457858449067
  max_bin: 135
  max_depth: 7
  max_leaves: 60
  n_estimators: 2000
  objective: reg:squarederror
  subsample: 0.9
  tree_method: hist
