stages:
  data_ingestion:
    cmd: python src/wine_reg/e_pipeline/stg_01_data_ingestion.py
    deps:
      - src/wine_reg/e_pipeline/stg_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/downloaded
      - artifacts/data_ingestion/extracted

  data_transformation:
    cmd: python src/wine_reg/e_pipeline/stg_02_data_transformation.py
    deps:
      - src/wine_reg/e_pipeline/stg_02_data_transformation.py
      - config/config.yaml
    outs:
      - artifacts/data_transformation

  model_trainer:
    cmd: python src/wine_reg/e_pipeline/stg_03_model_training.py
    deps:
      - src/wine_reg/e_pipeline/stg_03_model_training.py
      - globalparams.yaml
      - config/config.yaml
      - params.yaml
      - artifacts/data_ingestion
      - artifacts/data_transformation
    outs:
      - artifacts/model_trainer
      - bestparams.yaml

  model_eval:
    cmd: python src/wine_reg/e_pipeline/stg_04_model_eval.py
    deps:
      - src/wine_reg/e_pipeline/stg_04_model_eval.py
      - config/config.yaml
      - bestparams.yaml
      - artifacts/data_transformation
      - artifacts/model_trainer
