artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/winequality-data.zip
  downloaded_dir: artifacts/data_ingestion/downloaded
  extracted_dir: artifacts/data_ingestion/extracted
  file_path: artifacts/data_ingestion/downloaded/wine_data.zip

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/extracted/winequality-red.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: trained_models.joblib
  target: quality

model_eval:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/trained_models.joblib
  eval_results: artifacts/model_trainer/eval_results.joblib
  best_params: artifacts/model_trainer/best_params.joblib
  mlflow_uri: https://dagshub.com/vikramviky123/reg_wine_quality.mlflow
